
apiVersion: apps/v1
kind: Deployment
metadata:
  name: concert-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: concert-app
  template:
    metadata:
      labels:
        app: concert-app
    spec:
      containers:
        - image: kwangko/concert:dev_30
          imagePullPolicy: Always
          name: concert-project
          ports:
            - containerPort: 8080
              protocol: TCP



