apiVersion: v1
kind: Service
metadata:
  name: concert-svc
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: concert-app
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: concert-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: concert-app
  template:
    metadata:
      labels:
        app: concert-app
    spec:
      containers:
        - image: kwangko/concert:dev_24
          imagePullPolicy: Always
          name: concert-project
          ports:
            - containerPort: 8080
              protocol: TCP



